#!/usr/bin/env ruby
# Exports the exact Sources phase of the historical Telegraph Xcode target for
# Theos. It deliberately fails on an ambiguous file reference rather than
# silently compiling a different same-named source file.

require 'digest'

root = File.expand_path('../..', __dir__)
project = File.join(root, 'Telegraph.xcodeproj/project.pbxproj')
text = File.read(project)

phase = text[/D08805A8156E8F3600311537 \/\* Sources \*\/ = \{.*?\n\t\t\};/m]
abort 'Telegraph Sources phase was not found' unless phase

build_refs = phase.scan(/^\s*([0-9A-F]{24}) \/\* .*? in Sources \*\//).flatten
build_files = text.scan(/^\s*([0-9A-F]{24}) \/\* .*? in Sources \*\/ = \{isa = PBXBuildFile; fileRef = ([0-9A-F]{24}) /).to_h
file_paths = text.scan(/^\s*([0-9A-F]{24}) \/\* .*? \*\/ = \{isa = PBXFileReference;.*?\bpath = (.*?);/).to_h
all_files = Dir.glob(File.join(root, '**', '*')).select { |path| File.file?(path) }
files_by_basename = all_files.group_by { |path| File.basename(path) }

missing = []
sources = build_refs.filter_map do |build_ref|
  file_ref = build_files[build_ref]
  if file_ref.nil?
    missing << "PBXBuildFile:#{build_ref}"
    next
  end
  raw_path = file_paths[file_ref]
  if raw_path.nil?
    missing << "PBXFileReference:#{file_ref}"
    next
  end
  raw_path = raw_path.delete('"')
  direct = File.join(root, raw_path)
  if File.file?(direct)
    direct
  else
    matches = (files_by_basename[File.basename(raw_path)] || []).uniq
    if matches.empty?
      missing << raw_path
      next
    end
    if matches.length > 1
      preferred_roots = %w[Telegraph legacy/TL/TL legacy/TL legacy/TelegraphKit thirdparty submodules]
      preferred = preferred_roots.lazy.map do |directory|
        matches.select { |path| path.start_with?(File.join(root, directory) + '/') }
      end.find { |candidates| !candidates.empty? }
      if preferred
        matches = preferred
      end
    end
    if matches.length > 1
      digests = matches.map { |path| Digest::SHA256.file(path).hexdigest }.uniq
      matches = [matches.sort.first] if digests.length == 1
    end
    abort "Ambiguous source #{raw_path}: #{matches.join(', ')}" if matches.length > 1
    matches.first
  end
end

relative_sources = sources.map { |path| '../../' + path.delete_prefix(root + '/') }.uniq.sort
File.write(File.join(__dir__, 'Sources.mk'), "# Generated by generate_manifest.rb; do not edit.\nTWELVIUM_SOURCES := \\\n  #{relative_sources.join(" \\\n  ")}\n")
File.write(File.join(__dir__, 'MissingSources.txt'), missing.sort.join("\n") + (missing.empty? ? '' : "\n"))
puts "Wrote Sources.mk with #{relative_sources.length} source files; #{missing.length} referenced sources are absent (see MissingSources.txt)."
